language: swift

osx_image: xcode9.3

before_install:
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks
  - gem install cocoapods
  - pod install

script:
  - xcodebuild clean test -workspace DemoKKBOXOpenAPI.xcworkspace -scheme DemoKKBOXOpenAPITests -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' -configuration Debug -enableCodeCoverage YES | xcpretty


after_success:
    - bash <(curl -s https://codecov.io/bash) -J DemoKKBOXOpenAPI

notifications:
  email:
    on_success: never
    on_failure: change
