language: swift

osx_image: xcode9.2

before_install:
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks
  - gem install cocoapods
  - pod install

script:
  - xcodebuild clean build test -workspace DemoKKBOXOpenAPI.xcworkspace -scheme DemoKKBOXOpenAPI -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' -configuration Debug -enableCodeCoverage YES | xcpretty


after_success:
    - bash <(curl -s https://codecov.io/bash) -J 'DemoKKBOXOpenAPISwift'

notifications:
  email:
    on_success: never
    on_failure: change
